# Generated by Django 3.0 on 2019-12-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('recursos', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTurisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.Avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.Comentarios')),
                ('enderecos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.Enderecos')),
                ('recurso', models.ManyToManyField(to='recursos.Recursos')),
            ],
        ),
    ]
