# Generated by Django 3.0 on 2019-12-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturisco',
            name='enderecos',
        ),
    ]
