# Generated by Django 3.0 on 2019-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
        ('core', '0002_auto_20191207_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisco',
            name='recurso',
            field=models.ManyToManyField(to='recursos.Recursos'),
        ),
    ]
