# Generated by Django 3.0 on 2019-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontoturisco_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisco',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
    ]
