# Generated by Django 3.0 on 2019-12-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturisco_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisco',
            name='Avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
