# Generated by Django 3.0 on 2019-12-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_pontoturisco_avaliacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturisco',
            old_name='Avaliacoes',
            new_name='avaliacoes',
        ),
        migrations.AddField(
            model_name='pontoturisco',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Enderecos'),
            preserve_default=False,
        ),
    ]
